//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Life_Simulator.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Life_Simulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абрамов
        ///Авдеев
        ///Агафонов
        ///Аксёнов
        ///Александров
        ///Алексеев
        ///Андреев
        ///Анисимов
        ///Антонов
        ///Артемьев
        ///Архипов
        ///Афанасьев
        ///Баранов
        ///Белов
        ///Белозёров
        ///Белоусов
        ///Беляев
        ///Беляков
        ///Беспалов
        ///Бирюков
        ///Блинов
        ///Блохин
        ///Бобров
        ///Бобылёв
        ///Богданов
        ///Большаков
        ///Борисов
        ///Брагин
        ///Буров
        ///Быков
        ///Васильев
        ///Веселов
        ///Виноградов
        ///Вишняков
        ///Владимиров
        ///Власов
        ///Волков
        ///Воробьёв
        ///Воронов
        ///Воронцов
        ///Гаврилов
        ///Галкин
        ///Герасимов
        ///Голубев
        ///Горбачёв
        ///Горбунов
        ///Гордеев
        ///Горшков
        ///Григорьев
        ///Гришин
        ///Громов
        ///Гуляев
        ///Гурьев
        ///Гусев
        ///Гущин
        ///Давыдо [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string baseMenFam {
            get {
                return ResourceManager.GetString("baseMenFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авдей
        ///Авксентий
        ///Агафон
        ///Александр
        ///Алексей
        ///Альберт
        ///Альвиан
        ///Анатолий
        ///Андрей
        ///Антон
        ///Антонин
        ///Аристарх
        ///Аркадий
        ///Арсений
        ///Артём
        ///Богдан
        ///Борис
        ///Бронислав
        ///Вадим
        ///Валентин
        ///Валерий
        ///Валерьян
        ///Варлам
        ///Василий
        ///Виктор
        ///Виталий
        ///Владимир
        ///Владислав
        ///Владлен
        ///Всеволод
        ///Вячеслав
        ///Геласий
        ///Геннадий
        ///Георгий
        ///Герман
        ///Германн
        ///Глеб
        ///Гордей
        ///Григорий
        ///Дамир
        ///Даниил
        ///Демьян
        ///Денис
        ///Дмитрий
        ///Донателло
        ///Евгений
        ///Евсей
        ///Егор
        ///Еремей
        ///Ефим
        ///Иван
        ///Игнатий
        ///Игорь
        ///Илья
        ///Ириней
        ///Ким
        ///Кондрат
        ///Константин
        ///Куприян
        ///Лаврент [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string baseMenName {
            get {
                return ResourceManager.GetString("baseMenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авдеевич
        ///Авксентьевич
        ///Агафонович
        ///Александрович
        ///Алексеевич
        ///Альбертович
        ///Альвианович
        ///Анатольевич
        ///Андреевич
        ///Антонинович
        ///Антонович
        ///Аристархович
        ///Аркадьевич
        ///Арсеньевич
        ///Артёмович
        ///Богданович
        ///Борисович
        ///Брониславович
        ///Вадимович
        ///Валентинович
        ///Валерьевич
        ///Валерьянович
        ///Варламович
        ///Васильевич
        ///Викторович
        ///Витальевич
        ///Владимирович
        ///Владиславович
        ///Владленович
        ///Всеволодович
        ///Вячеславович
        ///Геласьевич
        ///Геннадьевич
        ///Георгьевич
        ///Германнович
        ///Германович
        ///Глебович
        ///Гордеевич
        ///Григорьевич
        ///Дамирович
        ///Даниилович
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string baseMenOtec {
            get {
                return ResourceManager.GetString("baseMenOtec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абрамова
        ///Авдеева
        ///Агафонова
        ///Аксёнова
        ///Александрова
        ///Алексеева
        ///Андреева
        ///Анисимова
        ///Антонова
        ///Артемьева
        ///Архипова
        ///Афанасьева
        ///Баранова
        ///Белова
        ///Белозёрова
        ///Белоусова
        ///Беляева
        ///Белякова
        ///Беспалова
        ///Бирюкова
        ///Блинова
        ///Блохина
        ///Боброва
        ///Бобылёва
        ///Богданова
        ///Большакова
        ///Борисова
        ///Брагина
        ///Бурова
        ///Быкова
        ///Васильева
        ///Веселова
        ///Виноградова
        ///Вишнякова
        ///Владимирова
        ///Власова
        ///Волкова
        ///Воробьёва
        ///Воронова
        ///Воронцова
        ///Гаврилова
        ///Галкина
        ///Герасимова
        ///Голубева
        ///Горбачёва
        ///Горбунова
        ///Гордеева
        ///Горшкова
        ///Григорьева
        ///Гри [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string baseWomenFam {
            get {
                return ResourceManager.GetString("baseWomenFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аврора
        ///Агата
        ///Аглая
        ///Агния
        ///Аделина
        ///Адель
        ///Адриана
        ///Азалия
        ///Айгуль
        ///Аида
        ///Аксинья
        ///Алевтина
        ///Александра
        ///Алёна
        ///Алина
        ///Алиса
        ///Алия
        ///Алла
        ///Алсу
        ///Альбина
        ///Альфия
        ///Амелия
        ///Амина
        ///Анастасия
        ///Ангелина
        ///Анжела
        ///Анита
        ///Анна
        ///Антонина
        ///Анфиса
        ///Ариадна
        ///Ариана
        ///Арина
        ///Ася
        ///Белла
        ///Валентина
        ///Валерия
        ///Варвара
        ///Василина
        ///Василиса
        ///Венера
        ///Вера
        ///Вероника
        ///Виктория
        ///Виолетта
        ///Владлена
        ///Галина
        ///Гузель
        ///Гульназ
        ///Гульнара
        ///Дана
        ///Дарина
        ///Дарья
        ///Джамиля
        ///Диана
        ///Дина
        ///Динара
        ///Доминика
        ///Ева
        ///Евангелина
        ///Евдокия
        ///Екатерина
        ///Ел [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string baseWomenName {
            get {
                return ResourceManager.GetString("baseWomenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авдеевна
        ///Авксентьевна
        ///Агафоновна
        ///Александровна
        ///Алексеевна
        ///Альбертовна
        ///Альвиановна
        ///Анатольевна
        ///Андреевна
        ///Антониновна
        ///Антоновна
        ///Аристарховна
        ///Аркадьевна
        ///Арсеньевна
        ///Артёмовна
        ///Богдановна
        ///Борисовна
        ///Брониславовна
        ///Вадимовна
        ///Валентиновна
        ///Валерьевна
        ///Валерьяновна
        ///Варламовна
        ///Васильевна
        ///Викторовна
        ///Витальевна
        ///Владимировна
        ///Владиславовна
        ///Владленовна
        ///Всеволодовна
        ///Вячеславовна
        ///Геласьевна
        ///Геннадьевна
        ///Георгьевна
        ///Германновна
        ///Германовна
        ///Глебовна
        ///Гордеевна
        ///Григорьевна
        ///Дамировна
        ///Данииловна
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string baseWomenOtec {
            get {
                return ResourceManager.GetString("baseWomenOtec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eys {
            get {
                object obj = ResourceManager.GetObject("eys", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eys2 {
            get {
                object obj = ResourceManager.GetObject("eys2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eys3 {
            get {
                object obj = ResourceManager.GetObject("eys3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lips {
            get {
                object obj = ResourceManager.GetObject("lips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lips2 {
            get {
                object obj = ResourceManager.GetObject("lips2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lips3 {
            get {
                object obj = ResourceManager.GetObject("lips3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap man_face {
            get {
                object obj = ResourceManager.GetObject("man_face", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nose {
            get {
                object obj = ResourceManager.GetObject("nose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nose2 {
            get {
                object obj = ResourceManager.GetObject("nose2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nose3 {
            get {
                object obj = ResourceManager.GetObject("nose3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woman_face {
            get {
                object obj = ResourceManager.GetObject("woman_face", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
